name: Return the version extracted from the .version file

inputs:
  working-directory:
    required: true

outputs:
  version:
    value: ${{ steps.get_version.outputs.VERSION }}

runs:
  using: composite

  steps:
    - id: get_version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        VERSION=$(head -1 .version)
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
