name: Publish release to npm

inputs:
  package:
    required: true
  node-version:
    required: true
  version:
    required: true
  require-build:
    default: true
  release-directory:
    default: './'

runs:
  using: composite

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: npm ci --include=dev

    - name: Build package
      if: inputs.require-build == 'true'
      shell: bash
      run: npx turbo run build --filter="{./packages/*}"

    - name: Publish release to NPM
      working-directory: packages/${{ inputs.package }}
      shell: bash
      run: |
        if [[ "${VERSION}" == *"beta"* ]]; then
          TAG="beta"
        elif [[ "${VERSION}" == *"alpha"* ]]; then
          TAG="alpha"
        else
          TAG="latest"
        fi
        npm publish --provenance --tag $TAG
      env:
        VERSION: ${{ inputs.version }}